version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./ml:/app/ml        # modelo XGBoost accesible sin rebuildar imagen
      - ./alembic:/app/alembic
    restart: unless-stopped
